CREATE DATABASE Projekat123;

CREATE TABLE Osoba(
	OsobaID INT PRIMARY KEY,
	Ime VARCHAR(20) NOT NULL,
	Prezime VARCHAR(20) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Adresa VARCHAR(50) NOT NULL,
	BrojKartice VARCHAR(16) NOT NULL,
	OsnovniJezikID INT NOT NULL
);

CREATE TABLE Klijent(
	KlijentID INT PRIMARY KEY,
	OsobaID INT NOT NULL,
	Visina FLOAT NOT NULL,
	Tezina FLOAT NOT NULL,
	ZdravstvenoStanje VARCHAR(200)
);

ALTER TABLE Klijent ADD CONSTRAINT OsobaIDFK1 FOREIGN KEY (OsobaID) REFERENCES Osoba(OsobaID);

CREATE TABLE Trener(
	TrenerID INT PRIMARY KEY,
	OsobaID INT NOT NULL,
	Diploma IMAGE NOT NULL,
	Sertifikat IMAGE NOT NULL,
	Zvanje VARCHAR(30) NOT NULL
);

ALTER TABLE Trener ADD CONSTRAINT OsobaIDFK2 FOREIGN KEY (OsobaID) REFERENCES Osoba(OsobaID);

CREATE TABLE Korisnik(
	KorisnikID INT PRIMARY KEY,
	OsobaID INT NOT NULL,
	KorisnickoIme VARCHAR(20) NOT NULL,
	Lozinka VARCHAR(20) NOT NULL
);

ALTER TABLE Korisnik ADD CONSTRAINT OsobaIDFK3 FOREIGN KEY (OsobaID) REFERENCES Osoba(OsobaID);

CREATE TABLE Jezik(
	JezikID INT PRIMARY KEY,
	Naziv VARCHAR(20) NOT NULL
);

ALTER TABLE Osoba ADD CONSTRAINT JezikIDFK1 FOREIGN KEY (OsnovniJezikID) REFERENCES Jezik(JezikID);

CREATE TABLE ListaDodatnihJezika(
	OsobaID INT NOT NULL,
	JezikID INT NOT NULL
);

ALTER TABLE ListaDodatnihJezika ADD CONSTRAINT OsobaIDFK4 FOREIGN KEY (OsobaID) REFERENCES Osoba(OsobaID);

ALTER TABLE ListaDodatnihJezika ADD CONSTRAINT JezikIDFK2 FOREIGN KEY (JezikID) REFERENCES Jezik(JezikID);

ALTER TABLE ListaDodatnihJezika ADD CONSTRAINT LDJPK PRIMARY KEY (OsobaID, JezikID);

CREATE TABLE Rekvizit(
	RekvizitID INT PRIMARY KEY,
	Naziv VARCHAR(30) NOT NULL,
	Opis VARCHAR(200)
);

CREATE TABLE ListaKlijentRekvizit(
	KlijentID INT NOT NULL,
	RekvizitID INT NOT NULL
);

ALTER TABLE ListaKlijentRekvizit ADD CONSTRAINT KlijentIDFK1 FOREIGN KEY (KlijentID) REFERENCES Klijent(KlijentID);

ALTER TABLE ListaKlijentRekvizit ADD CONSTRAINT RekvizitIDFK1 FOREIGN KEY (RekvizitID) REFERENCES Rekvizit(RekvizitID);

ALTER TABLE ListaKlijentRekvizit ADD CONSTRAINT LKPPK PRIMARY KEY (KlijentID, RekvizitID);

CREATE TABLE Cilj(
	CiljID INT PRIMARY KEY,
	Naziv VARCHAR(30) NOT NULL,
	Opis VARCHAR(200)
);

CREATE TABLE ListaKlijentCilj(
	KlijentID INT NOT NULL,
	CiljID INT NOT NULL
);

ALTER TABLE ListaKlijentCilj ADD CONSTRAINT KlijentIDFK2 FOREIGN KEY (KlijentID) REFERENCES Klijent(KlijentID);

ALTER TABLE ListaKlijentCilj ADD CONSTRAINT CiljIDFK1 FOREIGN KEY (CiljID) REFERENCES Cilj(CiljID);

ALTER TABLE ListaKlijentCilj ADD CONSTRAINT LKCPK PRIMARY KEY (KlijentID, CiljID);

CREATE TABLE Termin(
	TerminID INT PRIMARY KEY,
	TrenerID INT NOT NULL,
	Datum DATE NOT NULL,
	VREME TIME NOT NULL,
	Slobodan BIT NOT NULL
);

ALTER TABLE Termin ADD CONSTRAINT TrenerIDFK1 FOREIGN KEY (TrenerID) REFERENCES Trener(TrenerID);

CREATE TABLE Trening(
	TreningID INT PRIMARY KEY,
	KlijentID INT NOT NULL,
	TrenerID INT NOT NULL,
	TerminID INT NOT NULL,
	PlanTreninga VARCHAR(500),
	OcenaKlijenta INT,
	OcenaTrenera INT
);

ALTER TABLE Trening ADD CONSTRAINT KlijentIDFK3 FOREIGN KEY (KlijentID) REFERENCES Klijent(KlijentID);

ALTER TABLE Trening ADD CONSTRAINT TrenerIDFK2 FOREIGN KEY (TrenerID) REFERENCES Trener(TrenerID);

ALTER TABLE Trening ADD CONSTRAINT TerminIDFK1 FOREIGN KEY (TerminID) REFERENCES Termin(TerminID);